### ISSUE TITLE
ulua在ios下面用的是lua原生vm，跟slua用的luajit有啥好比的？

### ISSUE THREAD

**Issue by jarjin** [qiankanglai/unity_lua_benchmark#2]
稍微懂lua的人都知道luajit比luavm要快，但是在luajit目前不兼容mac u5，在ios下面必须2套字节码打包，而且需要在iPhone、iPad设备上面极其复杂麻烦，因此ulua才退而求其次选择统一字节码的luavm，但是性能还可以接受，不影响开发，但是从数值上面就不好看，这个测评没啥好说的，别忽悠新手入门人就行，Unity公司官方的测评是不是更权威些？？？

**Comment by qiankanglai** [comment]
1. 我承认我自己就是新手，如果能提供一些具体指导最好：譬如我做的测试有哪些不足，应该怎么改比较好？
2. 不知道您说的官方评测是哪一块？之前在uLua网站上有看到一个链接，不知道是不是指的这个。
3. 我整个代码公开，数据公开，仅供参考而已。我自己并没有任何倾向性，说要用哪个、不要用哪个。

**Comment by qiankanglai** [comment]
没有标注清楚是我的问题，但是我不明白为什么你会说“别忽悠新手入门人就行”
我其实主要是因为找不到官方提供的具体测试例子，所以才自己做了一份。如果您觉得我那边做的不对或者不够好，请指教一下我立刻修改，或者PR的形式也完全可以接受。
我也不想因为我自己知识不足给他人误导。

**Comment by jarjin** [comment]
先把ulua的mac+ios底层luavm换成luajit再说，才是同一起跑线，关于误导，是因为slua以unity开发新手不懂为因，一贯以忽悠别人自己多牛逼，实际上都是用特局部片面的来误导人。ulua之所以现在105款上线游戏，腾讯、网易、完美、畅游、巨人、盛大都在用，不是slua忽悠别人能信的，人家会自己测试，这并不是针对你本人，别多想。

**Comment by jarjin** [comment]
还有，虽然ulua目前使用者份额最大，但是从去年开始已经停止更新快半年，否是修修补补，但是它延伸出来的新版引擎tolua #才是当下我们正在维护的，如果测试用tolua #来测试吧。https://github.com/topameng/tolua

**Comment by jarjin** [comment]
ulua的老版案例：http://www.ulua.org/showcase.html

**Comment by qiankanglai** [comment]
恩，ulua的luajit这块有教程或者文档或者demo么？我把这个也加进去

我在网上看到了ulua和slua的论战，但是我先声明我没有任何倾向性（实际上，前天以前这两个框架我一个都没碰过……）。只不过我发现网上有相关讨论，但是没有实际可以跑的项目，所以自己动手做了一个而已。

任何对这个有疑问或者建议的，都可以加进来，我也很欢迎PR

tolua这个别人也给我提了issue，今天晚上我会抽空弄一下。

**Comment by qiankanglai** [comment]
那ulua的luajit还要做么？还是说直接做tolua的

**Comment by jarjin** [comment]
你可以直接测试tolua #，它本身提供性能测试例子。

**Comment by qiankanglai** [comment]
OK 顺便请教下tolua也是原生vm和luajit都有么？

**Comment by jarjin** [comment]
tolua在mac osx是luavm，因为unity跟luajit2.1不兼容，ios貌似已经替换成luajit，我不是作者，我只是ulua群主，作者是蒙哥，有情况ulua_tolua技术讨论群③ 434341400

**Comment by qiankanglai** [comment]
行吧...我刚加了群

反正我就是这么一个态度：这个benchmark在我有精力的条件下我会一直维护；如果你觉得测试方法不对或者不完善，或者数据有问题，跟我说怎么改，或者你改好了我直接merge也行~

我最后再表述一下：这个项目的出发点就是**比较Unity中执行Lua脚本各个方法的性能**。至于技术外的选择问题，我一概不予交流，因为这个东西的正确性太模糊，最后很大几率会沦为骂战。

就像你这个issue "ulua在ios下面用的是lua原生vm，跟slua用的luajit有啥好比的？" ，对我来说确实是可以比较的；开发易用性这个应该是使用者自己考虑的，而且有的开发者能接受有的不能接受，本来就是众口难调。

数据仅供参考，大家爱用啥用啥，爱信不信，就这样咯

**Comment by jarjin** [comment]
比较性能没问题，我也赞同，但是前提是得给用户交代清楚了，我说的是luajit跟luavm没什么可比性，没有ulua或者slua之前，luajit性能就比luavm高几倍，这是它们本身存在的差距，跟ulua、slua毫无关系，并不代表你拿着手枪打赢了拿着菜刀的人你的就牛啥，如果大家都是手枪对手枪，才公平。不公平的评测给小白用户看了，他不懂，他就这样认为谁行，谁不行，一开始用着挺高兴，到后期遇到各种坑，把用户丢那里不管了，这种不负责任的行为，就是我说的误导。你维护这个挺好，但是一定要全面，别片面，那就是给用户做了很多的好事。

**Comment by qiankanglai** [comment]
不知能否提供一下uLua/sLua/toLua在各个平台上究竟用的是luajit还是luavm的信息
我想把这个直接放到结果比较的图上方，加粗说明下

我确实是这方面的新手，担心自己搞错了引起误导

**Comment by qiankanglai** [comment]
不知能否提供一下uLua/sLua/toLua在各个平台上究竟用的是luajit还是luavm的信息？我想把这个直接放到结果比较的图上方，加粗说明下

我确实是这方面的新手，担心自己搞错了引起误导。反正不管一个解决方案到底支持了几种lua，我就会都测试一下，尽量做到公平~
